spring:
  datasource:
    url: jdbc:h2:file:~/db.data
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    static-path-pattern: /static/**
  h2:
    console:
      enabled: true
  resources:
    static-locations: classpath:/static,file:${IMAGE_ROOT:~/image}

file:
  image-root-location: ${IMAGE_ROOT:~/image}
