CREATE TABLE IF NOT EXISTS location (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  brief VARCHAR(512) NOT NULL,
  content VARCHAR(8000) NOT NULL,
  image VARCHAR(250) NOT NULL
);